### ISSUE TITLE
GError: ERROR: duplicate key value violates unique constraint "index_scaptimony_xccdf_results_on_name"

### ISSUE THREAD

**Issue by cristi1979** [OpenSCAP/scaptimony#19]
The upgrade to latest version of foreman was done a few weeks ago via puppet. All was fine at that time.

Today we updated the foreman puppet modules and the run tried to execute Foreman::Rake[db:seed]. This is the error we got:

    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: rake aborted!
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: PGError: ERROR: duplicate key value violates unique constraint "index_scaptimony_xccdf_results_on_name"
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: DETAIL: Key (name)=(pass) already exists.
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: : INSERT INTO "scaptimony_xccdf_results" ("name") VALUES ($1) RETURNING "id"
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns:
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Tasks: TOP => db:seed
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: (See full trace by running task with --trace)
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/03-auth_sources.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/03-permissions.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/03-roles.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/04-admin.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/05-taxonomies.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/06-architectures.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/07-config_templates.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/08-partition_tables.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/10-installation_media.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/11-smart_proxy_features.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/13-compute_profiles.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/15-bookmarks.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: Seeding /usr/share/foreman/db/seeds.d/16-mail_notifications.rb
    Notice: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]/returns: All seed files executed
    Error: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]:     Failed to call refresh: /usr/sbin/foreman-rake db:seed returned 1 instead of one of [0]
    Error: /Stage[main]/Foreman::Database/Foreman::Rake[db:seed]/Exec[foreman-rake-db:seed]: /usr/sbin/foreman-rake db:seed returned 1 instead of one of [0]

**Comment by isimluk** [comment]
Thanks for report!

Is it possible that you have older SCAPtimony installed? I have seen similar issue being fixed by @shlomizadok in da1f146c73f93e904088369e533b9bffc550bccf. Please confirm that you are using SCAPtimony 0.2.0. Thanks!

**Comment by cristi1979** [comment]
# rpm -qa | grep -i SCAPtimony
ruby193-rubygem-scaptimony-0.2.0-1.el7.centos.noarch

**Comment by isimluk** [comment]
Ok, thanks!

This issue shall be fixed in da1f146.
